apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: go-app-deployment  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: go-app  
  template:  
    metadata:  
      labels:  
        app: go-app  
    spec:  
      containers:  
      - name: go-app  
        image: tbikash62/app:0.0.2      
        env:  
        - name: PORT  
          value: "9090" # Set the build argument as an environment variable  

---

apiVersion: v1  
kind: Service  
metadata:  
  name: go-app-service  
spec:  
  type: NodePort  
  ports:  
    - port: 9091  
      targetPort: 9090  
      nodePort: 30090 # NodePort range is 30000-32767  
  selector:  
    app: go-app  